env:
- TERM=dumb

language: groovy
jdk: oraclejdk8

before_cache:
- for lockFile in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $lockFile;
  done

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

addons:
  apt:
    packages:
    - bash

install: true
script: ./gradlew clean build

after_success: ./gradlew jacocoTestReport coveralls
after_failure: ./gradlew clean check --debug
